[package]
name = "day06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_2023_common = {path = "../advent_2023_common"}
nom = "7.1.3"
